namespace CandyShop.API.Enums;
// public enum ProductCategory
// {
//     Empty,
//     Chocolate, 
//     HardCandy, 
//     GummyCandy, 
//     Caramel, 
//     Toffee, 
//     Fudge, 
//     Lollipops, 
//     Nougat, 
//     Marshmallows, 
//     Licorice, 
//     JellyBeans, 
//     Taffy, 
//     Truffles, 
//     Bonbons, 
//     CandyCorn
// }
